# Generated by Django 3.2.13 on 2022-07-02 07:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='ニックネーム')),
                ('email', models.EmailField(max_length=255, null=True, verbose_name='Eメールアドレス')),
                ('message', models.TextField(verbose_name='メッセージ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='ニックネーム')),
                ('email', models.EmailField(max_length=255, null=True, verbose_name='メールアドレス')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('message', models.TextField(verbose_name='メッセージ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='MarkdownFile',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='account_role_id',
            new_name='account_role',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='category_id',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='draft',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=32, verbose_name='カテゴリー名'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=32, verbose_name='タグ名'),
        ),
        migrations.AddField(
            model_name='comment',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.thread'),
        ),
    ]
